 -- POPULATING THE DROP-DOWN
SELECT DISTINCT LEFT(A.FIRST_NAME, 1) AS FNAME
FROM CUSTOMER A
ORDER BY 1 ASC;

SELECT DISTINCT LEFT(A.LAST_NAME, 1) AS L_N
FROM CUSTOMER A
ORDER BY 1 ASC;

 -- RESULTS OF THE DROP-DOWN SELECT
SELECT 
  DISTINCT A.CUSTOMER_ID, 
  CONCAT(A.FIRST_NAME, ' ', A.LAST_NAME) AS NAME, 
  CASE A.ACTIVE WHEN 1 THEN 'active' WHEN 0 THEN 'inactive' END AS STATUS
FROM CUSTOMER A 
WHERE A.FIRST_NAME LIKE 'A%' -- VARIABLE
ORDER BY 1 ASC;

SELECT 
  DISTINCT A.CUSTOMER_ID, 
  CONCAT(A.FIRST_NAME, ' ', A.LAST_NAME) AS NAME, 
  CASE A.ACTIVE WHEN 1 THEN 'active' WHEN 0 THEN 'inactive' END AS STATUS
FROM CUSTOMER A 
WHERE A.LAST_NAME LIKE 'A%' -- VARIABLE
ORDER BY 1 ASC;

-- RESULTS OF CUSTOMER LINK
SELECT A.NAME AS Category, COUNT(B.FILM_ID) AS NUMBER_RENTED
FROM CATEGORY A, FILM B,  RENTAL C, INVENTORY D, FILM_CATEGORY E
WHERE C.INVENTORY_ID = D.INVENTORY_ID
AND D.FILM_ID = B.FILM_ID
AND B.FILM_ID = E.FILM_ID
AND E.CATEGORY_ID = A.CATEGORY_ID
AND C.CUSTOMER_ID = 9 -- VARIABLE
GROUP BY A.NAME
ORDER BY 2 DESC, 1 ASC;

SELECT COUNT(Y.CATEGORY) AS CAETGORIES, SUM(Y.NUMBER_RENTED) AS FILMS FROM
(SELECT A.NAME AS Category, COUNT(B.FILM_ID) AS NUMBER_RENTED
FROM CATEGORY A, FILM B,  RENTAL C, INVENTORY D, FILM_CATEGORY E
WHERE C.INVENTORY_ID = D.INVENTORY_ID
AND D.FILM_ID = B.FILM_ID
AND B.FILM_ID = E.FILM_ID
AND E.CATEGORY_ID = A.CATEGORY_ID
AND C.CUSTOMER_ID = 9 -- VARIABLE
GROUP BY A.NAME
ORDER BY 2 DESC, 1 ASC)Y;

SELECT CONCAT(A.FIRST_NAME, ' ', A.LAST_NAME) AS CUSTOMER_NAME
FROM  CUSTOMER A
WHERE A.CUSTOMER_ID = 9;